name: Update Fortune

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-fortune:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install fortune
        run: sudo apt-get update && sudo apt-get install -y fortune-mod
      
      - name: Generate fortune and update README
        run: |
          fortune > README.md
      
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "literally ur fortune if you see this"
          git push
